package main

const (
	EQ            = " = "
	NEQ           = " != "
	GT            = " > "
	GTE           = " >= "
	LT            = " < "
	LTE           = " <= "
	AND           = " AND "
	OR            = " OR "
	COMMA         = ", "
	IN            = " IN "
	NOT_IN        = " NOT IN "
	LIKE          = " LIKE "
	LEFT_BRACKET  = "("
	RIGHT_BRACKET = ")"
	ORDER_BY      = " ORDER BY "
	LIMIT         = " LIMIT "
	FORCE_INDEX   = " FORCE INDEX "
	Q             = "?"
	QUOTE         = "`"
	DEFAULT       = "DEFAULT"
	TRUECOND      = "1=1"
	NOTFOUNDCOND  = "1!=1"
)

const (
	MUST_BE_NIL_ERR_MSG = "field must be nil."
	REQUIRED_ERR_MSG    = "field is required and must NOT be nil."
	EQ_ERR_MSG          = "value must equal to %+v"
	NEQ_ERR_MSG         = "value must different to %+v"
	IN_ERR_MSG          = "value must in list %+v"
	NOT_IN_ERR_MSG      = "value must NOT in list %+v"
	LT_ERR_MSG          = "value must less than %+v"
	LTE_ERR_MSG         = "value must less than or equal to %+v"
	GT_ERR_MSG          = "value must greater than %+v"
	GTE_ERR_MSG         = "value must greater than or equal to %+v"
	MUST_EMPTY_ERR_MSG  = "field value must be empty"
	NOT_EMPTY_ERR_MSG   = "field value must NOT be empty"
	MAX_LEN_ERR_MSG     = "len(value)=%d must less than max_len=%d"
	MIN_LEN_ERR_MSG     = "len(value)=%d must greater than min_len=%d"
	LEN_EQ_ERR_MSG      = "len(value)=%d must equal to expected_len=%d"
	DUPLICATE_ERR_MSG   = "value must not be duplicated"
)
